// Generated by gencpp from file ros_tutorials_topic/MsgTutorial.msg
// DO NOT EDIT!


#ifndef ROS_TUTORIALS_TOPIC_MESSAGE_MSGTUTORIAL_H
#define ROS_TUTORIALS_TOPIC_MESSAGE_MSGTUTORIAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_tutorials_topic
{
template <class ContainerAllocator>
struct MsgTutorial_
{
  typedef MsgTutorial_<ContainerAllocator> Type;

  MsgTutorial_()
    : pmsdata(0)  {
    }
  MsgTutorial_(const ContainerAllocator& _alloc)
    : pmsdata(0)  {
  (void)_alloc;
    }



   typedef int32_t _pmsdata_type;
  _pmsdata_type pmsdata;





  typedef boost::shared_ptr< ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator> const> ConstPtr;

}; // struct MsgTutorial_

typedef ::ros_tutorials_topic::MsgTutorial_<std::allocator<void> > MsgTutorial;

typedef boost::shared_ptr< ::ros_tutorials_topic::MsgTutorial > MsgTutorialPtr;
typedef boost::shared_ptr< ::ros_tutorials_topic::MsgTutorial const> MsgTutorialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_tutorials_topic

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ros_tutorials_topic': ['/home/pi/catkin_ws/src/ros_tutorials_topic/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ce25d4fb844ef5878b2c0a5c88477b7";
  }

  static const char* value(const ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ce25d4fb844ef58ULL;
  static const uint64_t static_value2 = 0x78b2c0a5c88477b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_tutorials_topic/MsgTutorial";
  }

  static const char* value(const ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 pmsdata\n"
;
  }

  static const char* value(const ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pmsdata);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MsgTutorial_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_tutorials_topic::MsgTutorial_<ContainerAllocator>& v)
  {
    s << indent << "pmsdata: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pmsdata);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TUTORIALS_TOPIC_MESSAGE_MSGTUTORIAL_H
